### ISSUE TITLE
Complete blockchain functionality (backend)

### ISSUE THREAD

**Issue by taageera** [alkalaminstitute/bunyaan_poc#11]
- [x] Complete blockchain functionality as is for version 1.
- [x] Incorporate broadcast of pending transactions.
- [x] Incorporate function to pay towards down-payment.
- [x] Incorporate function to distribute down-payment
- [x] Incorporate function to deduct from loan.

**Comment by smaronesy** [comment]
The core Blockchain functionality is complete
